# Generated by Django 5.2.8 on 2025-11-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("complaints", "0003_complaintupdate_complaint_district_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_id", models.IntegerField()),
                ("cluster_name", models.CharField(max_length=200)),
                ("keywords", models.JSONField(default=list)),
                ("complaint_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-complaint_count"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_vector", models.JSONField()),
                ("similarity_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.complaintcluster",
                    ),
                ),
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="complaints.complaint",
                    ),
                ),
            ],
        ),
    ]
